### ISSUE TITLE
Add WithContext() function

### ISSUE THREAD

**Issue by edrickezra** [rapidashorg/errwrap#1]
## Description

Add `ErrorWrapper.WithContext()` function to migrate `ErrorWrapper.WithData()` usage. Currently, `ErrorWrapper.WithData()` produces more duplicated lines, hence we can use `context.Context` to inject the data. Additionally, we can use `ErrorDefinition.New()` for our context injection, so we don't need to call additional functions.

## Tasks

- [ ]  Implement `WithContext()` function
- [ ] (*optional*) Inject the context in `ErrorDefinition.New()` function
- [ ] (*optional*) Modify `ErrorWrapper.AdditionalData` to `map[string]interface{}`, removing `Line` field.

Thanks
